In [36]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("iris.csv")
df.columns = ["X1", "X2", "X3","X4", "Y"]
df.head()


X1   X2   X3   X4            Y
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [7]:
df = pd.read_csv("AI.csv",index_col=0)

df.head()


Tear Production Sex     Age Spectacle rescription Astigmatism Recommendation
1         Reduced   M   Young                 Myope         Yes      Lifestyle
2         Reduced   F     Old                 Myope          No         Street
3          Normal   M     Old          Hypermetrope         Yes      Lifestyle
4          Normal   M   Young          Hypermetrope          No      Polarized
5         Reduced   F  Middle                 Myope          No         Street

In [6]:
df.shape

(15, 7)

In [9]:
X=df.values[:,0:5]
Y=df.values[:,5]

In [10]:
X

array([['Reduced', 'M', 'Young', 'Myope', 'Yes'],
       ['Reduced', 'F', 'Old', 'Myope', 'No'],
       ['Normal', 'M', 'Old', 'Hypermetrope', 'Yes'],
       ['Normal', 'M', 'Young', 'Hypermetrope', 'No'],
       ['Reduced', 'F', 'Middle', 'Myope', 'No'],
       ['Normal', 'F', 'Middle', 'Hypermetrope', 'Yes'],
       ['Normal', 'M', 'Young', 'Hypermetrope', 'No'],
       ['Reduced', 'M', 'Young', 'Hypermetrope', 'Yes'],
       ['Normal', 'M', 'Old', 'Myope', 'No'],
       ['Normal', 'M', 'Middle', 'Myope', 'Yes'],
       ['Reduced', 'F', 'Middle', 'Myope', 'No'],
       ['Reduced', 'F', 'Old', 'Hypermetrope', 'Yes'],
       ['Normal', 'M', 'Young', 'Myope', 'No'],
       ['Reduced', 'F', 'Old', 'Hypermetrope', 'Yes'],
       ['Normal', 'F', 'Old', 'Hypermetrope', 'Yes']], dtype=object)

In [11]:
Y

array(['Lifestyle', 'Street', 'Lifestyle', 'Polarized', 'Street',
       'Lifestyle', 'Polarized', 'Lifestyle', 'Street', 'Polarized',
       'Street', 'Polarized', 'Lifestyle', 'Polarized', 'Lifestyle'],
      dtype=object)

In [12]:
from sklearn import preprocessing
X.shape

(15, 5)

In [13]:
X2=X
le_X=preprocessing.LabelEncoder()
X2[:, 0] = le_X.fit_transform(X[:, 0])
X2[:, 1] = le_X.fit_transform(X[:, 1])
X2[:, 2] = le_X.fit_transform(X[:, 2])
X2[:, 3] = le_X.fit_transform(X[:, 3])
X2[:, 4] = le_X.fit_transform(X[:, 4])
X2

array([[1, 1, 2, 1, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 2, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 2, 0, 0],
       [1, 1, 2, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 2, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1]], dtype=object)

In [15]:
le_Y = preprocessing.LabelEncoder()
y2 = le_Y.fit_transform(Y)
y2


array([0, 2, 0, 1, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 0], dtype=int64)

In [16]:
enc = preprocessing.OneHotEncoder()
enc.fit(X2)
X2_enc = enc.transform(X2).toarray()
X2_enc.shape


(15, 11)

In [17]:
X2_enc

array([[0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.],
       [1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.],
       [0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0.],
       [0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.]])

In [27]:
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split( X2_enc, y2, test_size = 0.1)

In [31]:
from sklearn import tree
dtree=tree.DecisionTreeClassifier(criterion='gini')
dtree.fit(X2_enc,y2)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [32]:
Y_pred = dtree.predict(testX)
print(Y_pred)
print("Accuracy: \n", dtree.score(testX, testY))


[1 2]
Accuracy: 
 1.0


In [35]:
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(dtree, out_file=dot_data, filled=True, rounded=True, special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())


InvocationException: GraphViz's executables not found