In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv('AI33.csv')

In [2]:

data.head()

Age   Sex   Monthly Income   Marital   Service   Extra 
0    54     0             3000         1       100       0
1    59     0             4000         0       600      54
2    38     1             7800         0       200      31
3    18     0             8500         0       600     311
4    27     1            14000         1       100     211

In [4]:
from sklearn.cluster import KMeans
startpts = np.array([[54, 0, 3000, 1,100,0],
                     [22, 0, 7900, 0,200,31],
                     [22, 1, 18000, 1,400,303]])
km=KMeans(3,init=startpts)

X=data[['Age ', 'Sex ', 'Monthly Income ', 'Marital ', 'Service ','Extra ']]
km.fit(X)
km.predict(X)

/srv/conda/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:896: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


array([0, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1], dtype=int32)

In [7]:
from sklearn import preprocessing
min_max_scaler=preprocessing.MinMaxScaler()
X_trans=min_max_scaler.fit_transform(X)
print(X_trans)

[[0.88095238 0.         0.         1.         0.         0.        ]
 [1.         0.         0.02666667 0.         0.33333333 0.17363344]
 [0.5        1.         0.128      0.         0.06666667 0.09967846]
 [0.02380952 0.         0.14666667 0.         0.33333333 1.        ]
 [0.23809524 1.         0.29333333 1.         0.         0.67845659]
 [0.28571429 0.         0.74666667 1.         1.         0.08038585]
 [0.         1.         0.12       0.         0.33333333 0.81672026]
 [0.11904762 0.         0.13066667 0.         0.06666667 0.09967846]
 [0.4047619  1.         0.57866667 0.         0.         0.02250804]
 [0.69047619 0.         0.7496     1.         0.33333333 0.        ]
 [0.52380952 0.         0.48       1.         0.46666667 0.20578778]
 [0.42857143 0.         0.72       0.         1.         0.        ]
 [0.52380952 1.         1.         1.         1.         0.1607717 ]
 [0.02380952 1.         0.128      0.         0.6        0.93247588]
 [0.11904762 1.         0.4       

In [9]:
startpts2 = np.array([[0.88095238, 0, 0,1,0,0],
                     [0.11904762,0,0.13066667,0,0.06666667,0.09967846],
                     [0.11904762,1, 0.4,1,0.2,0.97427653]])
km2=KMeans(3,init=startpts2)

km2.fit(X_trans)
km2.predict(X_trans)

/srv/conda/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:896: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


array([0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 0, 1, 2, 2, 2], dtype=int32)