In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("cardiac.csv")

df.head()

bhr  basebp  basedp  pkhr  sbp     dp  dose  maxhr  %mphr(b)  mbp  ...    \
0   92     103    9476   114   86   9804    40    100        74  121  ...     
1   62     139    8618   120  158  18960    40    120        82  158  ...     
2   62     139    8618   120  157  18840    40    120        82  157  ...     
3   93     118   10974   118  105  12390    30    118        72  105  ...     
4   89     103    9167   129  173  22317    40    129        69  176  ...     

   newMI  newPTCA  newCABG  hxofHT  hxofdm  hxofcig  hxofMI  hxofPTCA  \
0      0        0        0       0       0      0.0       1         1   
1      1        0        0       0       1      0.0       1         0   
2      1        0        0       0       1      0.0       1         0   
3      0        0        0       0       0      0.0       0         0   
4      0        0        0       0       0      0.0       0         0   

   hxofCABG  death  
0         0      0  
1         0      0  
2         0      0  
3         0      0  
4         0      0  

[5 rows x 31 columns]

In [3]:
df.columns

Index(['bhr', 'basebp', 'basedp', 'pkhr', 'sbp', 'dp', 'dose', 'maxhr',
       '%mphr(b)', 'mbp', 'dpmaxdo', 'dobdose', 'age', 'gender', 'baseEF',
       'dobEF', 'chestpain', 'posECG', 'equivecg', 'restwma', 'posSE', 'newMI',
       'newPTCA', 'newCABG', 'hxofHT', 'hxofdm', 'hxofcig', 'hxofMI',
       'hxofPTCA', 'hxofCABG', 'death'],
      dtype='object')

In [4]:
df.describe()

bhr      basebp        basedp        pkhr         sbp  \
count   77.000000   77.000000     77.000000   77.000000   77.000000   
mean    76.025974  135.194805  10274.519481  120.493506  150.428571   
std     13.339666   22.666947   2447.163184   21.692603   36.615868   
min     50.000000  100.000000   5000.000000   75.000000   86.000000   
25%     67.000000  120.000000   8618.000000  108.000000  128.000000   
50%     75.000000  132.000000  10010.000000  120.000000  148.000000   
75%     86.000000  149.000000  11661.000000  131.000000  170.000000   
max    108.000000  192.000000  17604.000000  171.000000  309.000000   

                 dp       dose       maxhr    %mphr(b)         mbp    ...      \
count     77.000000  77.000000   77.000000   77.000000   77.000000    ...       
mean   18191.311688  32.272727  119.688312   78.675325  156.350649    ...       
std     5994.700079   8.450532   20.703585   14.237129   34.250150    ...       
min     8100.000000  15.000000   75.000000   50.000000  100.000000    ...       
25%    14208.000000  25.000000  107.000000   70.000000  134.000000    ...       
50%    17108.000000  35.000000  118.000000   77.000000  151.000000    ...       
75%    21450.000000  40.000000  131.000000   86.000000  174.000000    ...       
max    45114.000000  40.000000  171.000000  126.000000  309.000000    ...       

           newMI    newPTCA    newCABG     hxofHT     hxofdm    hxofcig  \
count  77.000000  77.000000  77.000000  77.000000  77.000000  77.000000   
mean    0.363636   0.051948   0.077922   0.324675   0.311688   0.181818   
std     0.484200   0.223377   0.269807   0.471324   0.466221   0.458179   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
50%     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
75%     1.000000   0.000000   0.000000   1.000000   1.000000   0.000000   
max     1.000000   1.000000   1.000000   1.000000   1.000000   1.500000   

          hxofMI   hxofPTCA   hxofCABG      death  
count  77.000000  77.000000  77.000000  77.000000  
mean    0.285714   0.038961   0.116883   0.077922  
std     0.454716   0.194771   0.323388   0.269807  
min     0.000000   0.000000   0.000000   0.000000  
25%     0.000000   0.000000   0.000000   0.000000  
50%     0.000000   0.000000   0.000000   0.000000  
75%     1.000000   0.000000   0.000000   0.000000  
max     1.000000   1.000000   1.000000   1.000000  

[8 rows x 31 columns]

In [5]:
from sklearn.model_selection import train_test_split
X=df.values[:,0:30]
Y=df.values[:,30]
trainX,testX,trainY,testY=train_test_split(X,Y,test_size=0.3)                                        

In [6]:
from sklearn import tree
dtree = tree.DecisionTreeClassifier(criterion="gini")
dtree.fit(trainX, trainY)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [7]:
Y_pred = dtree.predict(testX)
print(Y_pred)
print("Accuracy: \n", dtree.score(testX, testY))

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Accuracy: 
 0.9166666666666666


In [11]:
from sklearn import preprocessing
min_max_scaler=preprocessing.MinMaxScaler()
X_train=min_max_scaler.fit_transform(X)
train_scaled_X,testX,trainY,testY=train_test_split(X_train,Y,test_size=0.3)   
print(X_train)
X_train.shape

[[0.72413793 0.0326087  0.35512536 ... 1.         1.         0.        ]
 [0.20689655 0.42391304 0.28705173 ... 1.         0.         0.        ]
 [0.20689655 0.42391304 0.28705173 ... 1.         0.         0.        ]
 ...
 [0.46551724 0.32608696 0.39749286 ... 1.         0.         0.        ]
 [0.37931034 1.         0.70009521 ... 1.         0.         0.        ]
 [0.46551724 0.34782609 0.4097112  ... 0.         0.         0.        ]]


(77, 30)

In [9]:
from sklearn import tree
dtree = tree.DecisionTreeClassifier(criterion="gini")
dtree.fit(train_scaled_X, trainY)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [12]:
Y_pred = dtree.predict(testX)
print(Y_pred)
print("Accuracy: \n", dtree.score(testX, testY))

[0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
Accuracy: 
 0.875


In [18]:
for i in range(len(X_train)):
    for j in range (15):
        if X_train[i,j]<=0.25:
            X_train[i,j]=0
        elif X_train[i,j]>0.25 and X_train[i,j]<0.5:
            X_train[i,j]=3
        elif X_train[i,j]>=0.5 and X_train[i,j]<0.75:
            X_train[i,j]=2
        elif X_train[i,j]>=0.75 and X_train[i,j]<=1:
            X_train[i,j]=1
print(X_train)
X_interval=X_train

[[2. 0. 3. ... 1. 1. 0.]
 [0. 3. 3. ... 1. 0. 0.]
 [0. 3. 3. ... 1. 0. 0.]
 ...
 [3. 3. 3. ... 1. 0. 0.]
 [3. 1. 2. ... 1. 0. 0.]
 [3. 3. 3. ... 0. 0. 0.]]


In [19]:
train_interval_X,testX,trainY,testY=train_test_split(X_interval,Y,test_size=0.3)  
dtree = tree.DecisionTreeClassifier(criterion="gini")
dtree.fit(train_interval_X, trainY)
Y_pred = dtree.predict(testX)
print(Y_pred)
print("Accuracy: \n", dtree.score(testX, testY))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Accuracy: 
 0.9166666666666666
